### ISSUE TITLE
Plug in dev tools

### ISSUE THREAD

**Issue by chestnyh** [Andrij-Maksymyshyn/real-time-chat#6]
It's necessary to plug in some dev tools that allow us to keep code clean and prevent from stupid mistakes
eslint - https://eslint.org/docs/latest/use/getting-started
prettier - https://prettier.io/ (I see only config file, prettier is not installed)
husky - https://typicode.github.io/husky/#/

Feel free to collect information from different resources

**Comment by Andrij-Maksymyshyn** [comment]
Prettier & eslint I was added to devDependencies in server-part.
Prettier I was added to devDependencies in client-part. 
Unfortunately, I couldn't add eslint to client-part. It was giving an error that eslint-config-react-app is out of date.
And husky also failed to add to client-part. Used npx command mrm@2 lint-staged. It gave an error:
Installing lint-staged and husky...
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".        
warning "react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.3" has unmet peer dependency "typescript@>= 2.7".
warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has 
unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev 
|| >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
error Command failed with exit code 1.
C:\Users\User\AppData\Local\npm-cache\_npx\51762936ba23ccdb\node_modules\mrm\bin\mrm.js:56
                throw err;
                ^

Error: .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
    at Object.install (C:\Users\User\AppData\Local\npm-cache\_npx\51762936ba23ccdb\node_modules\husky\lib\index.js:20:15)
    at task (C:\Users\User\AppData\Local\npm-cache\_npx\51762936ba23ccdb\node_modules\mrm-task-lint-staged\index.js:214:8)
    at C:\Users\User\AppData\Local\npm-cache\_npx\51762936ba23ccdb\node_modules\mrm\src\index.js:170:20
    at C:\Users\User\AppData\Local\npm-cache\_npx\51762936ba23ccdb\node_modules\mrm\src\index.js:170:20


Node.js v18.12.1
